import React from 'react';

interface IInput {
  ReactThemeContext?: any;
  backgroundColor?: string;
  backgroundImage?: string;
  baseFontSize?: number;
  borderColor?: string;
  className?: any;
  color?: string;
  colorTheme?: string;
  disabled?: boolean;
  disabledBackgroundColor?: string;
  disabledColor?: string;
  error?: boolean;
  focusBackgroundColor?: string;
  focusColor?: string;
  fontFamily?: string;
  fontSize?: number;
  fontWeight?: number;
  getIsChangingState?: (isChanging: boolean) => void;
  height?: number;
  hoverBackgroundColor?: string;
  hoverColor?: string;
  id?: string;
  isNotClearable?: boolean;
  isNotUseDebounce?: boolean;
  isReadOnly?: boolean;
  isSeparateNumberFormat?: boolean;
  mask?: RegExp;
  max?: number;
  min?: number;
  name: string;
  onBlur?: (evt: any) => void;
  onChange?: (evt: React.ChangeEvent<HTMLInputElement>) => void;
  onClick?: (evt: any) => void;
  onFocus?: (evt: any) => void;
  onInput?: (evt: React.ChangeEvent<HTMLInputElement>) => void;
  onRemove?: (name: string, value?: string, evt?: any) => void;
  ref?: any;
  required?: boolean;
  step?: number;
  textAlign?: string;
  textMessage?: string;
  theme?: any;
  type?: string;
  value?: number | string;
  variant?: 'outlined' | 'text' | 'contained';
  width?: number;
  inputComponent?: any;
  placeholder?: string;
  textAling?: string;
  inputRef?: React.MutableRefObject<HTMLInputElement>;
}

export default IInput;
