import CSS from 'csstype';

type TBaseStyles = {
  id?: string;
  name?: string;
  display?: CSS.Property.Display;
  alignItems?: CSS.Property.AlignItems;
  flexDirection?: CSS.Property.FlexDirection;
  justifyContent?: CSS.Property.JustifyContent;
  alignSelf?: CSS.Property.AlignSelf;
  outline?: string;
  border?: CSS.Property.Border;
  borderBottom?: CSS.Property.BorderBottom;
  borderRadius?: number;
  gap?: number | string;
  backgroundColor?: CSS.Property.BackgroundColor;
  children?: any | Array<React.ReactNode>;
  className?: string;
  color?: CSS.Property.Color;
  disabled?: boolean;
  error?: boolean;
  fontFamily?: CSS.Property.FontFamily;
  fontSize?: number | string;
  fontWeight?: number;
  fontStyle?: string;
  whiteSpace?: CSS.Property.WhiteSpace;
  padding?: CSS.Property.Padding;
  paddingTop?: number | string;
  paddingBottom?: number | string;
  paddingRight?: number | string;
  paddingLeft?: number | string;
  margin?: CSS.Property.Margin;
  marginTop?: number | string;
  marginBottom?: number | string;
  marginLeft?: number | string;
  marginRight?: number | string;
  wordBreak?: number | string;
  flexGrow?: number;
  flexWrap?: CSS.Property.FlexWrap;
  lineHeight?: number;
  height?: number | string;
  minHeight?: number | string;
  maxHeight?: number | string;
  maxWidth?: number | string;
  minWidth?: number | string;
  width?: number | string;
  regExp?: RegExp;
  position?: CSS.Property.Position;
  textAlign?: CSS.Property.TextAlign;
  right?: number | string;
  left?: number | string;
  top?: number | string;
  bottom?: number | string;
  opacity?: CSS.Property.Opacity;
  transform?: string;
  overflowY?: string;
  zIndex?: number;
};

export default TBaseStyles;
