server {
  listen 80;
  server_name localhost;
    location / {
      # This would be the directory where your React app's static files are stored at
      root /src/dist;
      try_files $uri $uri/ /index.html;
      proxy_pass_request_headers on;
    }
}